language: python
python:
  - 3.8
  - 3.9
  - 3.10

install:
  - pip install -r requirements.txt

script:
  - ./setup.py test
  # - make docker-rest
  # - docker push ...
  # - make rpm
  # - make deb
  # - python3 appimage release.py qt

# Requires configuration of S3 credentials, see:
# https://docs.travis-ci.com/user/uploading-artifacts/
#addons:
#  artifacts: true
