FROM python:3.9-alpine
COPY requirements/ ./requirements
RUN pip3 install --no-cache-dir \
	-r requirements/common.txt \
	-r requirements/rest.txt
COPY . .
RUN PT_EXCLUDE_LIBS='ALL' python3 -m pip install -e .
ENTRYPOINT ["pytemplate_rest"]
