version: 2

jobs:
  tests:
      docker:
        - image: themattrix/tox
      steps:
        - checkout
        - run: pip install tox
        - run: git clone https://github.com/TODO/TODO.git
        - run: tox

workflows:
  version: 2
  myproj:
    jobs:
      - tests
