# Copied from: https://circleci.com/docs/language-python
version: 2.1
orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy: # this can be any name you choose
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
		  # force push when pushing to the heroku remote, see:
		  # https://devcenter.heroku.com/articles/git
          force: true

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
			# only deploy if the build_and_test job has completed
            - build_and_test
          filters:
            branches:
			  # only deploy when on main
              only: main
