#!/usr/bin/env python3
"""

"""

import argparse

def parse_args():
    parser = argparse.ArgumentParser("pytemplate Qt application")
    return parser.parse_args()

parse_args()

from pytemplate_qt.main import main

if __name__ == "__main__":
    main()
